1.up sampling 

2.down sampling

In [1]:
import numpy as np
import pandas as pd

np.random.seed(123)

# create a dataframe with 2 classes 
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [2]:
n_class_0, n_class_1

(900, 100)

In [3]:
# Create dataframe with imbalanced dataset
class_0 = pd.DataFrame({
    'feature 1' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature 2' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'target' : [0] * n_class_0 
})

class_1 = pd.DataFrame({
    'feature 1' : np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature 2' : np.random.normal(loc=2, scale=1, size=n_class_1),
    'target' : [1] * n_class_1 
})

In [4]:
df = pd.concat([class_0, class_1]).reset_index(drop=True)

In [5]:
df.head()

   feature 1  feature 2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [6]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [8]:
# Up Sampling : 
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [10]:
from sklearn.utils import resample

df_minority_upsampled = resample(df_minority, 
                                 replace=True, 
                                 n_samples=len(df_majority),
                                 random_state=42
                                ) # sample with replacement

In [11]:
df_minority_upsampled.shape

(900, 3)

In [12]:
df_minority_upsampled.head()

     feature 1  feature 2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [13]:
df_upsampled = pd.concat([df_majority, df_minority_upsampled])

In [14]:
df_upsampled

     feature 1  feature 2  target
0    -1.085631   0.551302       0
1     0.997345   0.419589       0
2     0.282978   1.815652       0
3    -1.506295  -0.252750       0
4    -0.578600  -0.292004       0
..         ...        ...     ...
952   1.188902   2.189189       1
965   3.919526   1.980541       1
976   2.810326   3.604614       1
942   3.621531   2.168229       1
974   1.160887   2.489203       1

[1800 rows x 3 columns]

In [15]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [ ]:
# Down Sampling 
import numpy as np
import pandas as pd

np.random.seed(123)

# create a dataframe with 2 classes 
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

import numpy as np
import pandas as pd

np.random.seed(123)

# create a dataframe with 2 classes 
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

df = pd.concat([class_0, class_1]).reset_index(drop=True)

# Down sampling 
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [18]:
from sklearn.utils import resample
df_majority_downsampled = resample(df_majority, replace=False,
                                   n_samples=len(df_minority),
                                   random_state=42
                                   )

In [19]:
df_majority_downsampled.value_counts()

feature 1  feature 2  target
-2.251535  -0.382087  0         1
-2.187086   0.499457  0         1
-2.152493  -0.518353  0         1
-2.008585  -0.422115  0         1
-1.895176   0.251075  0         1
                               ..
 1.805970  -1.757700  0         1
 1.861564  -1.788935  0         1
 1.984582  -0.682331  0         1
 2.559850  -0.085205  0         1
 3.571579   0.850721  0         1
Name: count, Length: 100, dtype: int64

In [20]:
df_majority_downsampled.shape

(100, 3)

In [21]:
df_downsampled = pd.concat([df_majority_downsampled, df_minority])

In [22]:
df_downsampled.shape

(200, 3)