In [4]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [5]:
df = pd.DataFrame({
    'color':['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [6]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [7]:
lbl_encoder = LabelEncoder()

In [8]:
lbl_encoder.fit_transform(df[['color']])

c:\Users\patil\OneDrive\Desktop\Udemy ML\venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [9]:
lbl_encoder.transform([['red']])

c:\Users\patil\OneDrive\Desktop\Udemy ML\venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [10]:
lbl_encoder.transform([['green']])

c:\Users\patil\OneDrive\Desktop\Udemy ML\venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

In [11]:
lbl_encoder.transform([['blue']])

c:\Users\patil\OneDrive\Desktop\Udemy ML\venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [ ]:
# Ordinal Encoding -> when the work is nominal then we can use the lable encoding but when we have to give some ranks in that case we use the ordinal encoding

In [19]:
from sklearn.preprocessing import OrdinalEncoder

In [20]:
df = pd.DataFrame(
    {
        'size' : ['small', 'medium', 'large', 'medium', 'small', 'large']
    }
)

In [21]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [23]:
# using the instance of ordinal encoder that is encoder in our case using that we will apply fit_transform to it 
encoder = OrdinalEncoder(categories=[['small', 'medium', 'large']]) # the categories decide what to give less value and what to give large value and that is based on the order of them we write 
# small will be having less value, medium will be having less than large, and large will be having the largest value or rank here in our case

In [24]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])