In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.DataFrame({
    'colors':['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [3]:
df.head()

  colors
0    red
1   blue
2  green
3  green
4    red

In [4]:
# Create an instance of one hot encoder
encoder = OneHotEncoder()

In [8]:
# perform fit and then transform 
encoded=encoder.fit_transform(df[['colors']]).toarray()

In [9]:
encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())

In [10]:
encoder_df

   colors_blue  colors_green  colors_red
0          0.0           0.0         1.0
1          1.0           0.0         0.0
2          0.0           1.0         0.0
3          0.0           1.0         0.0
4          0.0           0.0         1.0
5          1.0           0.0         0.0